language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - wget dist.neo4j.org/neo4j-community-2.1.2-unix.tar.gz
    - tar -xzf neo4j-community-2.1.2-unix.tar.gz
    - neo4j-community-2.1.2/bin/neo4j start
    - redis-server --daemonize yes --port 6380
    - sleep 3
    - composer self-update
    - composer install --prefer-source --no-interaction --dev


script:
    - phpunit --testsuite cms
    - phpunit --testsuite validators
    - phpunit --testsuite repositories

matrix:
    allow_failures:
        - php: 5.6
        - php: hhvm
    fast_finish: true

branches:
    only:
        - master
        - develop

services:
    - redis-server

notifications:
  slack:
    rooms:
      - vinelab:XWn6x3YfliIywgTlwwAQsLGs#agency